//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_to_Readers
    {
        public int Id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> reader_id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
